# Generated by Django 4.0.4 on 2022-06-02 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан в:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(blank=True, null=True, verbose_name='Приватный'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
