# Generated by Django 4.0.4 on 2022-06-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_post_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Приватный'),
        ),
    ]
